<?php
/**
 * General Function to handle any exception
 * It will be triggered by PHP when an exception occurs
 *
 * @param $e Exception an object with information about the exception
 * automatically generated by PHP when the function is triggered.
 */

function exceptionHandler($e) {
    $errors['mess'] = " Message: ".$e->getMessage();
    $errors['file'] = "File: ".$e->getFile();
    $errors['line'] = " Line: ".$e->getLine();

    if(DEVELOPMENT_MODE == true)
        return $errors;
    else
        return "Internal Server Error (status code 500)";
}

/**
 * Exception Handler Function to output JSON formatted exception messages
 */
function jsonExceptionHandler($e) {
    $response = new JSONResponse(exceptionHandler($e));
    $response->setMessage("Internal Server Error");
    $response->setStatusCode(500);
    echo $response->getData();
}

/**
 * Exception Handler Function to output HTML formatted exception messages
 */
function htmlExceptionHandler($e) {
    $response = new HTMLResponse(exceptionHandler($e));
    foreach ($response->getData() as $k => $value) {
        echo "<p>".$value."</p>";
    }

}